### ISSUE TITLE
Import scheme does not work with ts-loader v9

### ISSUE THREAD

**Issue by alexrudd2** [nornagon/saxi#144]
```
  ./src/ui.tsx + 9 modules 61.4 KiB [not cacheable] [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js!./src/style.css 18.9 KiB [built] [code generated]

ERROR in /Users/a.ruddick/Documents/github/saxi/src/ui.tsx
1:29-54
[tsl] ERROR in /Users/a.ruddick/Documents/github/saxi/src/ui.tsx(1,30)
      TS2792: Cannot find module '@rehooks/component-size'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
ts-loader-default_734d3b3c730a45e9

ERROR in /Users/a.ruddick/Documents/github/saxi/src/massager.ts
1:30-46
[tsl] ERROR in /Users/a.ruddick/Documents/github/saxi/src/massager.ts(1,31)
      TS2792: Cannot find module 'optimize-paths'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
```

The problem is the `import *` introduced in https://github.com/nornagon/saxi/commit/decf9ab0bfd80e593e89e26a0bbf8b55ebfd57ad.  It can be fixed by switching the import scheme, and adding `"moduleResolution": "node"`

**Comment by alexrudd2** [comment]
See https://github.com/alexrudd2/saxi/pull/38
